import { completeFromList } from '@codemirror/autocomplete';

// Provides a list of labels for CodeMirror completion
export const COMPLETIONS = completeFromList([
  {label: "-i", type: "flag"},
  {label: "-vcodec", type: "flag", detail: "selects video codec"},
  {label: "-acodec", type: "flag"},
  {label: "-f", type: "flag"},
  {label: "-r", type: "flag"},
  {label: "-s", type: "flag"},
  {label: "-t", type: "flag"},
  {label: "-b", type: "flag"},
  {label: "-ss", type: "flag"},
  {label: "-to", type: "flag"},
  {label: "-vn", type: "flag"},
  {label: "-an", type: "flag"},
  {label: "-preset", type: "flag"},
  {label: "-filter_complex", type: "flag"},
  {label: "-map", type: "flag"},
  {label: "-segment_time", type: "flag"},
  {label: "-segment_format", type: "flag"},
  {label: "-c:v", type: "flag"},
  {label: "-c:a", type: "flag"},
  {label: "-profile:v", type: "flag"},
  {label: "-y", type: "flag"},
  {label: "-q:v", type: "flag"},
  {label: "-maxrate", type: "flag"},
  {label: "-bufsize", type: "flag"},
  {label: "-threads", type: "flag"},
  {label: "-fpre", type: "flag"},
  {label: "-vpre", type: "flag"},
  {label: "-analyzer", type: "flag"},
  {label: "-af", type: "flag"},
  {label: "-b:a", type: "flag"},
  {label: "-scodec", type: "flag"},
  {label: "-metadata", type: "flag"},
  {label: "-copyts", type: "flag"},
  {label: "-copytb", type: "flag"},
  {label: "-toioptions", type: "flag"},
  {label: "-pix_fmt", type: "flag"},
  {label: "-qscale", type: "flag"},
  {label: "-qmin", type: "flag"},
  {label: "-qmax", type: "flag"},
  {label: "-loglevel", type: "flag"},
]);

