// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Command = 1,
  CommandName = 2,
  FlagPlusParameters = 3,
  Flag = 4,
  Parameter = 5,
  Argument = 6,
  String = 7
