// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOQOPOOOYOPO'#CfO`OPO'#CfQOOOOOOeOPO'#C_OOOO'#Cd'#CdOjOPO,59QOuOPO,59QOzOPO,59QO!POQO,58yOOOO-E6b-E6bO!XOQO1G.lO!aOPO1G.lOuOPO1G.lOOOO'#Ca'#CaO!lOPO1G.eO!qOPO7+$WO!yOQO7+$WO#ROPO7+$WOOOO7+$P7+$POOOO<<Gr<<GrO#^OPO<<GrO#fOQO<<GrOOOOAN=^AN=^O#nOPOAN=^OOOOG22xG22x",
  stateData: "#v~OQQOZPO~OQWOSSOZVO~OZXO~OSSOZZOXYa~OSSO~OZ]O~OU^OV^O~OU`OXYi~OSSOZaOXYi~OZcO~OZdOXYq~OUeOXYq~OSSOZfOXYq~OZgOXYy~OUhOXYy~OZiOXY!R~O",
  goto: "xZPPP[PdPPgPu]TPUV[]bR_XQUPUYU[bQ[VRb]RRO",
  nodeNames: "⚠ Command CommandName FlagAndParameter Flag Parameter Argument String",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ",p~R`OX!TXY#XYZ#XZ]!T]^#X^p!Tpq#Xqr!Trs#js}!T}!O%W!O#Y!T#Y#Z&[#Z;'S!T;'S;=`#R<%lO!TQ!Y]UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#p!T#q;'S!T;'S;=`#R<%lO!TQ#UP;=`<%l!T~#^SZ~XY#XYZ#X]^#Xpq#X~#mVOr#jrs$Ss#O#j#O#P$X#P;'S#j;'S;=`%Q<%lO#j~$XOV~~$[RO;'S#j;'S;=`$e;=`O#j~$hWOr#jrs$Ss#O#j#O#P$X#P;'S#j;'S;=`%Q;=`<%l#j<%lO#j~%TP;=`<%l#j~%ZT}!O%j![!]%y!c!}%y#R#S%y#T#o%y~%mS![!]%y!c!}%y#R#S%y#T#o%y~&OSS~![!]%y!c!}%y#R#S%y#T#o%yR&a_UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#Y!T#Y#Z'`#Z#p!T#q;'S!T;'S;=`#R<%lO!TR'e_UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#a!T#a#b(d#b#p!T#q;'S!T;'S;=`#R<%lO!TR(i_UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#d!T#d#e)h#e#p!T#q;'S!T;'S;=`#R<%lO!TR)m_UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#X!T#X#Y*l#Y#p!T#q;'S!T;'S;=`#R<%lO!TR*q_UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#Z!T#Z#[+p#[#p!T#q;'S!T;'S;=`#R<%lO!TR+w]UQQPOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q!^!T!_!`!T!b#O!T#P#p!T#q;'S!T;'S;=`#R<%lO!T",
  tokenizers: [0, 1],
  topRules: {"Command":[0,1]},
  tokenPrec: 0
})
