// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fOQOPOOOYOPO'#CgO`OPO'#CgQOOOOOOeOPO'#C_OOOO'#Cd'#CdOpOPO,59ROxOPO,59RO}OPO,59RO!SOQO,58yOOOO-E6b-E6bO!bOPO1G.mOxOPO1G.mOOOO'#Ca'#CaO!jOQO'#CeO!{OQO1G.eO#ZOPO7+$XOOOO,59P,59POOOO-E6c-E6c",
  stateData: "#c~OQQO[PO~OQWOSSO[VO~O[XOSRXYRX~OSSOYZa~OSSO~O[[O~OU]OV]OSRaYRa~OSSOYZi~O[aOSXXUXXVXXYXX~OU]OV]OSRiYRi~OSSOYZq~O",
  goto: "!Q[PPP]PePPiwP}]TPUVZ[`T^X_QUPUYUZ`QZVR`[Q_XRb_RRO",
  nodeNames: "⚠ Command CommandName FlagPlusParameters Flag Parameter Argument String",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "-V~R`OX!TXY#[YZ#[Z]!T]^#[^p!Tpq#[qr!Trs#ms}!T}!O%Z!O#Y!T#Y#Z&_#Z;'S!T;'S;=`#U<%lO!TQ!Y^UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#p!T#q;'S!T;'S;=`#U<%lO!TQ#XP;=`<%l!T~#aS[~XY#[YZ#[]^#[pq#[~#pVOr#mrs$Vs#O#m#O#P$[#P;'S#m;'S;=`%T<%lO#m~$[OV~~$_RO;'S#m;'S;=`$h;=`O#m~$kWOr#mrs$Vs#O#m#O#P$[#P;'S#m;'S;=`%T;=`<%l#m<%lO#m~%WP;=`<%l#m~%^T}!O%m![!]%|!c!}%|#R#S%|#T#o%|~%pS![!]%|!c!}%|#R#S%|#T#o%|~&RSS~![!]%|!c!}%|#R#S%|#T#o%|R&d`UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#Y!T#Y#Z'f#Z#p!T#q;'S!T;'S;=`#U<%lO!TR'k`UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#a!T#a#b(m#b#p!T#q;'S!T;'S;=`#U<%lO!TR(r`UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#d!T#d#e)t#e#p!T#q;'S!T;'S;=`#U<%lO!TR)y`UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#X!T#X#Y*{#Y#p!T#q;'S!T;'S;=`#U<%lO!TR+Q`UQOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#Z!T#Z#[,S#[#p!T#q;'S!T;'S;=`#U<%lO!TR,Z^UQQPOX!TZ]!T^p!Tqr!Tsz!T{!P!T!Q![!T!]!^!T!_!`!T!b#O!T#P#p!T#q;'S!T;'S;=`#U<%lO!T",
  tokenizers: [0, 1],
  topRules: {"Command":[0,1]},
  tokenPrec: 0
})
